### ISSUE TITLE
Reboot To Bootloader

### ISSUE THREAD

**Issue by superjax** [rosflight/rosflight_firmware#229]
This is becoming increasingly necessary as autopilots are buried in the UAVs

**Comment by cmcquinn** [comment]
@superjax I added a service for this to the code in the rosflight repo. Can you add me to that repo so I can make a branch with my changes?

**Comment by superjax** [comment]
Check your email

**Comment by cmcquinn** [comment]
I successfully tested my fix on a board. The changes are in reboot_to_bootloader branch on the rosflight repo.

**Comment by superjax** [comment]
Hey @cmcquinn, we typically don't "close" an issue until we merge the commit into a release branch (like `rc1.0`.  Thanks for putting this together.  When we get around to merging that in, then we will close this issue.

**Comment by cmcquinn** [comment]
I just realized today that this doesn't work properly. Sometimes the code will flash without issues, but doesn't run properly, and other times `make flash` returns an error before the firmware can be written 100%. I am going to do some research and see what we can do to fix this.
