### ISSUE TITLE
[Proposal] - Don't run controller if throttle is super low in multirotors

### ISSUE THREAD

**Issue by superjax** [rosflight/rosflight_firmware#230]
On some lighter multirotrs, the yaw rate command from arming the aircraft is significant enough that the multirotor wants to lift off when arming or disarming.  I propose not running the controller if throttle is below the `MOTOR_IDLE_THR` parameter value

I think we should talk about this before implementing @dpkoch, thoughts?

**Comment by dpkoch** [comment]
Possibly, it'd probably be okay but we should evaluate if there would be any non-negligible effects on stability. Another option would be to map an arming switch to avoid the issue.

**Comment by superjax** [comment]
This is included in #278.

**Comment by bsutherland333** [comment]
Fixed-wing tests have been completed.
