### ISSUE TITLE
Documentation: Emphasize GPS should output NMEA

### ISSUE THREAD

**Issue by Georacer** [rosflight/rosflight_firmware#322]
Hi again,

So, I'm reading through the documentation. [Here](http://docs.rosflight.org/en/latest/user-guide/hardware-setup/#wiring-diagram) hints that the GPS receiver is to be connected to the onboard computer, not the FC. Okay.

So I go over to ROSFlight to find the driver, specifically: [here](https://github.com/rosflight/rosflight/blob/8142d7a7e6775116eaf5eaefcfa0663ac4ab99a3/rosflight_utils/src/gps) and [here](https://github.com/rosflight/rosflight/blob/8142d7a7e6775116eaf5eaefcfa0663ac4ab99a3/rosflight_utils/src/libnmea_navsat_driver/driver.py).

These links tell me that the GPS should appear hard-coded at `tty/USB0` and be set up to output NMEA sentences at 115200 baud.

I think these settings should be stated somewhere in the documentation, as required for operation.

**Comment by bsutherland333** [comment]
With our current hardware we have the GPS connected directly to the FC rather than the onboard computer, and if a GPS needs to be connect to the onboard computer we're recommending that a 3rd party driver is used.
