### ISSUE TITLE
Add Configrator

### ISSUE THREAD

**Issue by hmz06967** [rosflight/rosflight_firmware#405]
https://github.com/hmz06967/rosflight-configrator 
I added configuration software support for your rc devices.

**Comment by bsutherland333** [comment]
I'm not certain what this configurator is suppose to do, if you're still interested in sharing it could you explain what it does in more detail?

**Comment by hmz06967** [comment]
The betaflight configurator program, which is the utility program of betaflight, compiled for the ROSFlight C software, supports Mavlink as a protocol and runs on Windows.
